bases:
- ../../base
resources:
- ../../../deployments/adminer.yml
- ../../../deployments/redis-admin.yml
- ../../../services/adminer.yml
- ../../../services/redis-admin.yml
- ./namespace.yaml
namespace: shopsys-ci
