imports:
    - { resource: forms.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\ShopBundle\Controller\:
        resource: '../../Controller/'
        public: true
        tags: ['controller.service_arguments']

    Shopsys\ShopBundle\Model\:
        resource: '../../Model/**/*{Facade,Factory}.php'

    League\Flysystem\MountManager:
        arguments:
            -
                local: '@local_filesystem'
                main: '@main_filesystem'

    Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory: ~

    Shopsys\FrameworkBundle\Model\Order\OrderFlowFactoryInterface: '@Shopsys\ShopBundle\Form\Front\Order\DomainAwareOrderFlowFactory'

    Shopsys\FrameworkBundle\Model\Article\ArticleDataFactoryInterface: '@Shopsys\ShopBundle\Model\Article\ArticleDataFactory'

    Shopsys\ShopBundle\Model\Category\CurrentCategoryResolver: ~

    League\Flysystem\FilesystemInterface: '@main_filesystem'

    Shopsys\FrameworkBundle\Model\Administrator\AdministratorDataFactoryInterface: '@Shopsys\ShopBundle\Model\Administrator\AdministratorDataFactory'

    Shopsys\FrameworkBundle\Model\Category\CategoryDataFactoryInterface: '@Shopsys\ShopBundle\Model\Category\CategoryDataFactory'

    Shopsys\FrameworkBundle\Model\Customer\UserDataFactoryInterface: '@Shopsys\ShopBundle\Model\Customer\UserDataFactory'

    Shopsys\FrameworkBundle\Model\Order\OrderDataFactoryInterface: '@Shopsys\ShopBundle\Model\Order\OrderDataFactory'

    Shopsys\ShopBundle\Model\Order\OrderDataMapper: ~

    Shopsys\FrameworkBundle\Model\Order\OrderDataMapper: '@Shopsys\ShopBundle\Model\Order\OrderDataMapper'

    Shopsys\FrameworkBundle\Model\Transport\TransportDataFactoryInterface: '@Shopsys\ShopBundle\Model\Transport\TransportDataFactory'

    Shopsys\FrameworkBundle\Model\Payment\PaymentDataFactoryInterface: '@Shopsys\ShopBundle\Model\Payment\PaymentDataFactory'

    Shopsys\FrameworkBundle\Model\Product\ProductDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\ProductDataFactory'

    Shopsys\FrameworkBundle\Model\Product\Brand\BrandDataFactoryInterface: '@Shopsys\ShopBundle\Model\Product\Brand\BrandDataFactory'

    doctrine.orm.is_pohoda_entity_manager:
      class: Shopsys\ShopBundle\Component\Doctrine\PohodaEntityManager
      lazy:  true # important, frontend does not need PohodaEntityManager, see ocramius/proxy-manager
      factory: [Shopsys\ShopBundle\Component\Doctrine\PohodaEntityManager, create]
      arguments:
        - '@doctrine.dbal.is_pohoda_connection'
        - '@doctrine.orm.is_pohoda_configuration'